export const phones = [{
    id: 1,
    img: 'https://media.currys.biz/i/currysprod/M10230581_black?$l-large$&fmt=auto',
    name: 'APPLE iPhone 13 - 128 GB, Midnight',
    price: '€689.00',
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 2,
    img: 'https://media.currys.biz/i/currysprod/M10254987_black?$l-large$&fmt=auto',
    name: 'APPLE iPhone 15 - 128 GB, Black',
    price: '€969.00',
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 3,
    img: 'https://media.currys.biz/i/currysprod/10197974_002?$l-large$&fmt=auto',
    name: 'APPLE iPhone 11 - 64 GB, Black',
    price: '€519.00',
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 4,
    img: 'https://media.currys.biz/i/currysprod/M10255035_blue?$l-large$&fmt=auto',
    name: 'APPLE iPhone 15 Pro Max - 256 GB, Blue Titanium',
    price: '€1,469.00',
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 5,
    img: 'https://media.currys.biz/i/currysprod/M10215597_purple?$l-large$&fmt=auto',
    name: 'APPLE iPhone 12 - 64 GB, Purple',
    price: '€539.00 ',
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 6,
    img: 'https://media.currys.biz/i/currysprod/M10254987_black?$l-large$&fmt=auto',
    name: 'APPLE iPhone 15 - 256 GB, Black',
    price: '€1,099.00',
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 7,
    img: 'https://media.currys.biz/i/currysprod/M10248085_black?$l-large$&fmt=auto',
    name: 'SAMSUNG Galaxy A14 - 64 GB, Black',
    price: '€159.00',
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 8,
    img: "https://media.currys.biz/i/currysprod/10259183?$l-large$&fmt=auto",
    name: "SAMSUNG Galaxy S23 FE 5G - 128 GB, Graphite",
    price: "€699.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 9,
    img: "https://media.currys.biz/i/currysprod/10248091?$l-large$&fmt=auto",
    name: "SAMSUNG Galaxy A54 5G - 128 GB, Awesome Black",
    price: "€509.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 10,
    img: "https://media.currys.biz/i/currysprod/M10246943_black?$l-large$&fmt=auto",
    name: "SAMSUNG Galaxy S23 Ultra - 256 GB, Phantom Black",
    price: "€1,459.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 11,
    img: "https://media.currys.biz/i/currysprod/M10246895_black?$l-large$&fmt=auto",
    name: "SAMSUNG Galaxy S23 - 128 GB, Phantom Black",
    price: "€999.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 12,
    img: "https://media.currys.biz/i/currysprod/10259167?$l-large$&fmt=auto",
    name: "SAMSUNG Galaxy S23 FE 5G - 256 GB, Mint",
    price: "€749.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 13,
    img: "https://media.currys.biz/i/currysprod/M10246998_cream?$l-large$&fmt=auto",
    name: "SAMSUNG Galaxy S23+ - 256 GB, Cream",
    price: "€1,249.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 14,
    img: "https://media.currys.biz/i/currysprod/M10246943_black?$l-large$&fmt=auto",
    name: "SAMSUNG Galaxy S23 Ultra - 512 GB, Phantom Black",
    price: "€1,649.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 15,
    img: "https://media.currys.biz/i/currysprod/10243722?$l-large$&fmt=auto",
    name: "GOOGLE Pixel 7 - 128 GB, Obsidian",
    price: "€539.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 16,
    img: "https://media.currys.biz/i/currysprod/10256450?$l-large$&fmt=auto",
    name: "GOOGLE Pixel 8 Pro - 128 GB, Obsidian",
    price: "€1,099.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 17,
    img: "https://media.currys.biz/i/currysprod/10243734?$l-large$&fmt=auto",
    name: "GOOGLE Pixel 7 Pro - 128 GB, Obsidian",
    price: "€879.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 18,
    img: "https://media.currys.biz/i/currysprod/M10247632_purple?$l-large$&fmt=auto",
    name: "OPPO Find N2 Flip - 256 GB, Moonlit Purple",
    price: "€1,019.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 19,
    img: "https://media.currys.biz/i/currysprod/10234976?$l-large$&fmt=auto",
    name: "OPPO A74 5G - 128 GB, Fluid Black",
    price: "€329.99",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
},
{
    id: 20,
    img: "https://media.currys.biz/i/currysprod/M10242845_gold?$l-large$&fmt=auto",
    name: "OPPO Reno8 5G - 256 GB, Shimmer Gold",
    price: "€509.00",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, totam nihil animi dignissimos, eligendi libero a sed officia amet sapiente iure molestiae ipsam culpa nisi natus accusamus quia architecto suscipit.",
}
];